# Generated by Django 3.1.2 on 2020-10-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cources',
            name='pay',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
