# Generated by Django 3.1.2 on 2020-10-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_cources_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainers',
            name='image',
            field=models.ImageField(default=1, upload_to='profile_pics'),
            preserve_default=False,
        ),
    ]
