# Generated by Django 3.1.2 on 2020-10-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_trainers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cources',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
