# Generated by Django 3.1.2 on 2020-10-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201012_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainers',
            name='l_description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
