# Generated by Django 3.1.2 on 2020-10-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_trainers_l_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cources',
            name='l_description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
