# Generated by Django 3.1.2 on 2020-10-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_cources_l_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('feedBack', models.CharField(max_length=10000)),
                ('pic', models.ImageField(upload_to='testimonials')),
            ],
        ),
    ]
