# Generated by Django 3.1.2 on 2020-12-04 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('w_number', models.IntegerField(max_length=11)),
                ('country', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=254)),
                ('cnic', models.IntegerField(max_length=30)),
                ('payment_method', models.CharField(max_length=30)),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cources')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trainers')),
            ],
        ),
    ]
